-- def single_dict() -> Single[Dict]: ...
SELECT a, b FROM test ORDER BY a LIMIT 1;

-- def single_list() -> Single[List]: ...
SELECT a, b FROM test ORDER BY a LIMIT 1;

-- def single_tuple() -> Single[Tuple]: ...
SELECT a, b FROM test ORDER BY a LIMIT 1;

-- def iterator_dict() -> Iterator[Dict]: ...
SELECT a, b FROM test ORDER BY a;

-- def iterator_list() -> Iterator[List]: ...
SELECT a, b FROM test ORDER BY a;

-- def iterator_tuple() -> Iterator[Tuple]: ...
SELECT a, b FROM test ORDER BY a;

-- def list_dict() -> List[Dict]: ...
SELECT a, b FROM test ORDER BY a;

-- def list_list() -> List[List]: ...
SELECT a, b FROM test ORDER BY a;

-- def list_tuple() -> List[Tuple]: ...
SELECT a, b FROM test ORDER BY a;
