-- def nothing() -> None: ...
SELECT NULL;

-- def single_dict() -> Single[Dict]: ...
SELECT 0 AS a, 'a' AS b;

-- def single_tuple() -> Single[Tuple]: ...
SELECT 0 AS a, 'a' AS b;

-- def single_value() -> Single[Value]: ...
SELECT 0 AS a;

-- def iterator_dict() -> Iterator[Dict]: ...
SELECT a, b FROM numbers;

-- def iterator_tuple() -> Iterator[Tuple]: ...
SELECT a, b FROM numbers;

-- def iterator_value() -> Iterator[Value]: ...
SELECT a FROM numbers;

-- def list_dict() -> List[Dict]: ...
SELECT a, b FROM numbers;

-- def list_tuple() -> List[Tuple]: ...
SELECT a, b FROM numbers;

-- def list_value() -> List[Value]: ...
SELECT a, b FROM numbers;

-- def dict_of_dicts_by_column_name() -> Dict['a', Dict]: ...
SELECT a, b FROM numbers;

-- def dict_of_tuples_by_column_name() -> Dict['a', Tuple]: ...
SELECT a, b FROM numbers;

-- def dict_of_values_by_column_name() -> Dict['a', Value]: ...
SELECT a, b FROM numbers;

-- def dict_of_dicts_by_column_index() -> Dict[0, Dict]: ...
SELECT a, b FROM numbers;

-- def dict_of_tuples_by_column_index() -> Dict[0, Tuple]: ...
SELECT a, b FROM numbers;

-- def dict_of_values_by_column_index() -> Dict[0, Value]: ...
SELECT a, b FROM numbers;

-- def dict_of_dicts_by_column_name_removed_key() -> Dict[-'a', Dict]: ...
SELECT a, b FROM numbers;

-- def dict_of_tuples_by_column_name_removed_key() -> Dict[-'a', Tuple]: ...
SELECT a, b FROM numbers;

-- def dict_of_values_by_column_name_removed_key() -> Dict[-'a', Value]: ...
SELECT a, b FROM numbers;

-- def dict_of_dicts_by_column_index_removed_key() -> Dict[-0, Dict]: ...
SELECT a, b FROM numbers;

-- def dict_of_tuples_by_column_index_removed_key() -> Dict[-0, Tuple]: ...
SELECT a, b FROM numbers;

-- def dict_of_values_by_column_index_removed_key() -> Dict[-0, Value]: ...
SELECT a, b FROM numbers;

-- def dict_of_tuples_by_column_name_out_of_range() -> Dict['z', Tuple]: ...
SELECT a, b FROM numbers;

-- def dict_of_tuples_by_column_index_out_of_range() -> Dict[3, Tuple]: ...
SELECT a, b FROM numbers;

-- def dict_of_empty_dicts() -> Dict[-0, Dict]: ...
SELECT a FROM numbers;

-- def dict_of_empty_tuples() -> Dict[-0, Tuple]: ...
SELECT a FROM numbers;

-- def dict_of_empty_singles() -> Dict[-0, Value]: ...
SELECT a FROM numbers;
