-- def nothing() -> None: ...
SELECT NULL;

-- def single_dict() -> Single[Dict]: ...
SELECT 0 AS a, 'a' AS b;

-- def single_list() -> Single[List]: ...
SELECT 0 AS a, 'a' AS b;

-- def single_tuple() -> Single[Tuple]: ...
SELECT 0 AS a, 'a' AS b;

-- def single_single() -> Single[Single]: ...
SELECT 0 AS a;

-- def iterator_dict() -> Iterator[Dict]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def iterator_list() -> Iterator[List]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def iterator_tuple() -> Iterator[Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def iterator_single() -> Iterator[Single]: ...
SELECT a FROM numbers a;

-- def list_dict() -> List[Dict]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def list_list() -> List[List]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def list_tuple() -> List[Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def list_single() -> List[Single]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_tuples_by_column_name() -> Dict['a', Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_tuples_by_column_index() -> Dict[0, Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_tuples_by_column_name_removed_key() -> Dict[-'a', Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_tuples_by_column_index_removed_key() -> Dict[-0, Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_tuples_by_column_name_out_of_range() -> Dict['z', Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_tuples_by_column_index_out_of_range() -> Dict[3, Tuple]: ...
SELECT a, substr('abc', a+1, 1) AS b FROM numbers a;

-- def dict_of_empty_dicts() -> Dict[-0, Dict]: ...
SELECT a FROM numbers a;

-- def dict_of_empty_lists() -> Dict[-0, List]: ...
SELECT a FROM numbers a;

-- def dict_of_empty_tuples() -> Dict[-0, Tuple]: ...
SELECT a FROM numbers a;

-- def dict_of_empty_singles() -> Dict[-0, Single]: ...
SELECT a FROM numbers a;
