-- def ping() -> Single[Dict]: ...
SELECT TRUE AS pong;

-- def swap_args(a: int = 0, b: str = 'a') -> Single[Tuple]: ...
SELECT :b AS a, :a AS b;

-- def create_test_table() -> None: ...
CREATE TABLE numbers (a integer);

-- def fill_test_table() -> None: ...
INSERT INTO numbers VALUES (0), (1), (2);
