-- def swap_args(a: int = 0, b: str = 'a') -> Single[Tuple]: ...
SELECT :b AS a, :a AS b;             -- sqlite3
SELECT $2::text AS a, $1::int AS b;  -- asyncpg
SELECT %(b)s AS a, %(a)s AS b;       -- others

-- def cleanup_test_table() -> None: ...
DROP TABLE IF EXISTS numbers;

-- def create_test_table() -> None: ...
CREATE TABLE numbers (a integer, b text);

-- def fill_test_table() -> None: ...
INSERT INTO numbers VALUES (0, 'a'), (1, 'b'), (2, 'c');
