name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install codecov
      - name: Run unit tests
        run: pytest -v -rs --cov-report=xml --cov=aesqlapius tests/
      - name: Push coverage info
        run: codecov
